### ISSUE TITLE
Double click doesn't work

### ISSUE THREAD

**Issue by kostaskas** [lazd/VoodooI2CGoodix#12]
## Description
Double click (tap) doesn't work

## Steps to reproduce

Try to double click an item on your desktop, you will see that it doesn't, just it's selected

## Expected behavior
When double clicking/taping on an icon, it should run and not just selected, like the one click/tap does

## Environment
 - **Computer**: Chuwi Minibook 8
 - **VoodooI2C version:** 2.3
 - **VoodooI2CGoodix version:** 0.2.3
 - **macOS Version:** 10.15.1

**Comment by lazd** [comment]
I've seen this as well. I find I need to click it many many times, then it'll launch. Seems like a timing issue.
