### ISSUE TITLE
Doesn't work on Big Sur 11.0 Beta 4

### ISSUE THREAD

**Issue by kostaskas** [lazd/VoodooI2CGoodix#18]
## Prerequisites

* [ ] I have followed the [VoodooI2C installation instructions](https://voodooi2c.github.io/#Installation/Installation)
* [ ] I have [patched my DSDT](https://github.com/alexandred/VoodooI2C-Patches)
* [ ] I have followed the [GPIO pinning guide](https://voodooi2c.github.io/#GPIO%20Pinning/GPIO%20Pinning)
* [ ] VoodooI2C recognizes my I2C controllers during a verbose boot
* [x] I have followed the [VoodooI2CGoodix installation instructions](https://github.com/lazd/VoodooI2CGoodix#installation)
* [x] I have tried tapping my screen and nothing happens

## Environment
 - **Computer**: Minibook 8
 - **VoodooI2C version:** 2.4.4
 - **VoodooI2CGoodix version:** 0.3.0
 - **macOS Version:** 11.0 Beta (20A5343j)

**Comment by kostaskas** [comment]
Used OC 0.6.0 but touch screen doesn't work, even with VooDooI2C 2.4.4 version

**Comment by lazd** [comment]
Interesting. No logs?

**Comment by kostaskas** [comment]
[systemlog.txt](https://github.com/lazd/VoodooI2CGoodix/files/5100883/systemlog.txt)
> Interesting. No logs?

Here you are with latest voodooI2C 😉 , if you need 2.3 version, I will send
